versions:
  # ensure the versions are in order, the newer the top
  active:
    - "v1.8.0"
    - "v1.7.1"
    - "v1.7.0"
    - "v1.6.1"
    - "v1.6.0"
    - "v1.5.1"
    - "v1.5.0"
    - "v1.4.1"
    - "v1.4.0"
    - "v1.3.2"
    - "v1.3.1"
    - "v1.3.0"
exceptions:
  # some images need be kept, e.g. vmdp is used by Windows VMs via container disk
  # image:tag is treated as plain text, not regex
  images:
    - "vmdp:2.5.4.2"
    - "vmdp:2.5.5"

